forms/baseform.py
from wtforms import Form


# 用于从form.errors中提取所有字符串类型的错误信息
# 以后可以通过form.messages得到所有字符串类型的错误信息，用于传递给渲染模板
class BaseForm(Form):
    @property
    def messages(self):
        message_list = []
        if self.errors:
            for error in self.errors.values():
                message_list.extend(error)
        return message_list

blueprints/cms.py
from flask import Blueprint, render_template, g, redirect, request, flash, url_for
from models.user import PermissionEnum
from decorators import permission_required
from models.user import UserModel, RoleModel
from models.post import PostModel
from forms.cms import AddStaffForm, EditStaffForm
from exts import db
from utils import restful

bp = Blueprint('cms', __name__, url_prefix='/cms')


# 管理页面的视图函数
@bp.get("")
def index():
    return render_template("cms/index.html")


# 如果当前用户不是员工，则不允许访问
@bp.before_request
def cms_before_request():
    if not hasattr(g, "user") or g.user.is_staff is False:
        return redirect("/")


@bp.context_processor
def cms_context_processor():
    return {"PermissionEnum": PermissionEnum}


@bp.get("/staff/list")
@permission_required(PermissionEnum.CMS_USER)
def staff_list():
    users = UserModel.query.filter_by(is_staff=True).all()
    return render_template("cms/staff_list.html", users=users)


@bp.route("/staff/add", methods=['GET', 'POST'])
@permission_required(PermissionEnum.CMS_USER)
def add_staff():
    if request.method == "GET":
        roles = RoleModel.query.all()
        return render_template("cms/add_staff.html", roles=roles)
    else:
        form = AddStaffForm(request.form)
        if form.validate():
            email = form.email.data
            role_id = form.role.data
            user = UserModel.query.filter_by(email=email).first()
            if not user:
                flash("没有此用户")
                return redirect(url_for("cms.add_staff"))
            user.is_staff = True
            user.role = RoleModel.query.get(role_id)
            db.session.commit()
            return redirect(url_for("cms.staff_list"))


# 编辑员工
@bp.route("/staff/edit/<string:user_id>", methods=['GET', 'POST'])
@permission_required(PermissionEnum.CMS_USER)
def edit_staff(user_id):
    user = UserModel.query.get(user_id)
    if request.method == 'GET':
        roles = RoleModel.query.all()
        return render_template("cms/edit_staff.html", user=user, roles=roles)
    else:
        form = EditStaffForm(request.form)
        if form.validate():
            is_staff = form.is_staff.data
            role_id = form.role.data
            user.is_staff = is_staff
            if user.role.id != role_id:
                user.role = RoleModel.query.get(role_id)
            db.session.commit()
            return redirect(url_for("cms.edit_staff", user_id=user_id))
        else:
            for message in form.messages:
                flash(message)
            return redirect(url_for("cms.edit_staff", user_id=user_id))


@bp.route("/users")
@permission_required(PermissionEnum.FRONT_USER)
def user_list():
    users = UserModel.query.filter_by(is_staff=False).all()
    return render_template("cms/users.html", users=users)


@bp.post("/users/active/<string:user_id>")
@permission_required(PermissionEnum.FRONT_USER)
def active_user(user_id):
    is_active = request.form.get("is_active", type=int)
    if is_active is None:
        return restful.param_error(message="请传入is_active参数")
    user = UserModel.query.filter_by(user_id)
    user.is_active = bool(is_active)
    db.session.commit()
    return restful.ok()


@bp.get("/posts")
@permission_required(PermissionEnum.POST)
def post_list():
    posts = PostModel.query.all()
    return render_template("cms/posts.html", posts=posts)


@bp.post("/posts/active/<int:post_id>")
def active_post(post_id):
    is_active = request.form.get("is_active", type=int)
    if is_active is None:
        return restful.param_error(message="请输入is_active参数")
    post = PostModel.query.get(post_id)
    post.is_active = bool(is_active)
    db.session.commit()
    return restful.ok()

blueprints/front.py
import os

from flask import Blueprint, request, render_template, jsonify, current_app, url_for, send_from_directory, g, flash, \
    redirect
from werkzeug.utils import secure_filename
from models.post import BoardModel, PostModel, CommentModel
from exts import csrf, db
from decorators import login_required
from forms.post import PublicPostForm
from utils import restful
from flask_paginate import Pagination

bp = Blueprint('front', __name__, url_prefix='')


# 发布帖子的视图
@bp.route("/post/public", methods=['GET', 'POST'])
@login_required
def public_post():
    if request.method == 'GET':
        boards = BoardModel.query.all()
        return render_template("front/public_post.html", boards=boards)
    else:
        form = PublicPostForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.title.data
            board_id = form.board_id.data
            post = PostModel(title=title, content=content, board_id=board_id, author=g.user)
            db.session.add(post)
            db.session.commit()
            return restful.ok()
        else:
            message = form.messages[0]
            return restful.param_error(message=message)


# 主页视图
@bp.route("/")
def index():
    boards = BoardModel.query.all()
    # 获取页码参数
    page = request.args.get("page", type=int, default=1)
    # 获取板块参数
    board_id = request.args.get("board_id", type=int, default=0)

    # 当前page的起始位置
    start = (page - 1) * current_app.config.get("PER_PAGE_COUNT")
    # 当前page下的结束位置
    end = start + current_app.config.get("PER_PAGE_COUNT")

    # 查询对象
    query_obj = PostModel.query.filter_by(is_active=True).order_by(PostModel.create_time.desc())

    if board_id:
        query_obj = query_obj.filter_by(board_id=board_id)

    # 总共有多少帖子
    total = query_obj.count()
    # 当前page下的帖子列表
    posts = query_obj.slice(start, end)
    # 分页对象
    pagination = Pagination(bs_version=4, page=page, total=total, outer_window=0, inner_window=2, alignment="center")

    context = {
        "posts": posts,
        "boards": boards,
        "pagination": pagination,
        "current_board": board_id
    }

    return render_template("front/index.html", **context)


@bp.get("/post/detail/<int:post_id>")
def post_detail(post_id):
    post = PostModel.query.get(post_id)
    post.read_count += 1
    db.session.commit()
    return render_template("front/post_detail.html", post=post)


# 把帖子id通过url参数传过来，然后通过表单获取评论内容
@bp.route("/post/<int:post_id>/comment")
@login_required
def public_comment(post_id):
    form = PublicPostForm(request.form)
    if form.validate():
        content = form.content.data
        comment = CommentModel(content=content, post_id=post_id, author=g.user)
        db.session.add(comment)
        db.session.commit()
    else:
        for message in form.messages:
            flash(message)
    return redirect(url_for("front.post_detail", post_id=post_id))


# 上传图片的视图函数
@bp.route("/upload/image")
@csrf.exempt
@login_required
def upload_image():
    f = request.files.get('image')
    extension = f.filename.split(".")[-1].lower()
    if extension not in ['jpg', 'gif', 'png', 'jpeg']:
        return jsonify({
            'errno': 400,
            "data": []
        })
    filename = secure_filename(f.filename)
    # 保存图片到默认路径
    f.save(os.path.join(current_app.config.get("UPLOAD_IMAGE_PATH"), filename))
    url = url_for('media.media_file', filename=filename)
    return jsonify({
        'errno': 0,
        "data": [{
            "url": url,
            "alt": "",
            "href": ""
        }]
    })

blueprints/user.py
import os
import random

from flask import Blueprint, render_template, request, current_app, redirect, url_for, flash, session, g
from exts import cache, db
from utils import restful
from forms.user import RegisterForm, LoginForm, EditProfileForm
from models.user import UserModel
from werkzeug.datastructures import CombinedMultiDict
from werkzeug.utils import secure_filename
from decorators import login_required

bp = Blueprint('user', __name__, url_prefix='/user')


@bp.route("/profile/edit")
@login_required
def edit_profile():
    form = EditProfileForm(CombinedMultiDict([request.form, request.files]))
    if form.validate():
        username = form.username.data
        avatar = form.avatar.data
        signature = form.signature.data
        # 如果上传了头像
        if avatar:
            # 生成安全的文件名
            filename = secure_filename(avatar.filename)
            # 拼接头像存储路径
            avatar_path = os.path.join(current_app.config.get("AVATARS_SAVE_PATH"), filename)
            # 保存文件
            avatar.save(avatar_path)
            # 设置头像的url
            g.user.avatar = url_for("media.media_file", filename=os.path.join("avatars", filename))
            g.user.username = username
            g.user.signature = signature
            db.session.commit()
            return redirect(url_for("user.profile", user_id=g.user_id))
        else:
            for message in form.messages:
                flash(message)
            return redirect(url_for("user.profile", user_id=g.user_id))


# 发送邮箱验证码，若发送成功，返回状态码200，否则返回状态码500
@bp.route('/mail/captcha')
def mail_captcha():
    try:
        email = request.args.get("mail")
        digits = [str(i) for i in list(range(0, 10))]
        captcha = ''.join(random.sample(digits, 4))
        subject = '注册验证码'
        body = "你的注册验证码是{}".format(captcha)
        current_app.celery.send_task('send_mail', (email, subject, body))

        # 将验证码存到redis
        cache.set(email, captcha, timeout=100)
        return restful.ok()
    except Exception as e:
        print(e)
        return restful.sever_error()


# 登录视图函数
@bp.route("/register", methods=['GET', 'POST'])
def register():
    if request.method == "GET":
        return render_template("front/register.html")
    else:
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            user = UserModel(email=email, username=username, password=password)

            db.session.add(user)
            db.session.commit()
            return redirect(url_for("user.login"))
        else:
            for message in form.messages:
                flash(message)
            return redirect(url_for("user.register"))


@bp.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == "GET":
        return render_template("front/login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            remember = form.remember.data
            user = UserModel.query.filter_by(email=email).first()
            if user and user.check_password(password):
                if not user.is_active:
                    flash("该用户已被禁用")
                    return redirect(url_for("user.login"))
                session['user_id'] = user.id
                if remember:
                    session.permanent = True
                return redirect("/")
            else:
                flash("邮箱或者密码错误")
                return redirect(url_for("user.login"))
        else:
            for message in form.messages:
                flash(message)
            return render_template("front/login.html")


@bp.route("/profile<string:user_id>")
def profile(user_id):
    user = UserModel.query.get(user_id)
    is_mine = False
    # 添加限制，访问自己的个人中心可以编辑，访问别人的个人中心不能编辑
    if hasattr(g, "user") and g.user == user_id:
        is_mine = True
    context = {
        'user': user,
        "is_mine": is_mine,
    }
    return render_template("front/profile.html", **context)


@bp.route("/logout")
def logout():
    session.clear()
    return redirect("/")

templates/front/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <link href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"></script>
  <script src="{{ url_for('static',filename='common/zlajax.js') }}"></script>
  <link rel="stylesheet" href="{{ url_for('static',filename='front/css/base.css') }}">
  <title>{% block title %}{% endblock %}</title>
  {% block head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">知了Python论坛</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">首页 <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <form class="form-inline my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="请输入关键字" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
    </form>
    <ul class="navbar-nav ml-4">
      {% if g.user %}
        {% if g.user.is_staff %}
          <li class="nav-item">
            <a href="{{ url_for('cms.index') }}" class="nav-link">管理系统</a>
          </li>
        {% endif %}
        <li class="nav-item">
          <a href="{{ url_for('user.profile',user_id=g.user.id) }}" class="nav-link">{{ g.user.username }}</a>
        </li>
        <li class="nav-item">
          <a href="{{ url_for("user.logout") }}" class="nav-link">退出登录</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.login') }}">登录</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('user.register') }}">注册</a>
        </li>
      {% endif %} 
    </ul>
  </div>
</nav>
<div class="main-container">
  {% block body %}{% endblock %}
</div>
</body>
</html>

templates/front/index.html
{% extends "front/base.html" %}

{% block title %}知了Python论坛{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static',filename='front/css/index.css') }}">
{% endblock %}

{% block body %}
    <div class="lg-container">
        <div class="post-group">
            <ul class="post-list-group">
                {% for post in posts %}
                    <li>
                        <div class="post-info-group">
                            <p class="post-title">
                                <a href="{{ url_for('front.post_detail',post_id=post.id) }}">{{ post.title }}</a>
                            </p>
                            <p class="post-info">
                                <span>作者：{{ post.author.username }}</span>
                                <span>发表时间：{{ post.create_time }}</span>
                                <span>评论：{{ post.comments.all()|length }}</span>
                            </p>
                        </div>
                    </li>
                {% endfor %}
            </ul>
            {{ pagination.links }}
        </div>
    </div>
    <div class="sm-container">
        <div style="padding-bottom:10px;">
            <a href="{{ url_for("front.public_post") }}" class="btn btn-warning btn-block">发布帖子</a>
        </div>
        <div class="list-group">
            {% if current_board %}
                <a href="/" class="list-group-item">所有板块</a>
            {% else %}
                <a href="/" class="list-group-item active">所有板块</a>
            {% endif %}
            {% for board in boards %}
                {% if board.id == current_board %}
                    <a href="{{ url_for('front.index',board_id=board.id) }}"
                       class="list-group-item active">{{ board.name }}</a>
                {% else %}
                    <a href="{{ url_for('front.index',board_id=board.id) }}"
                       class="list-group-item">{{ board.name }}</a>
                {% endif %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/front/login.html
{% extends 'front/base.html' %}

{% block title %}
  登录
{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{{ url_for('static',filename='front/css/sign.css') }}">
{% endblock %}

{% block body %}
  <h1 class="page-title">登录</h1>
  <div class="sign-box">
    <form action="{{ url_for('user.login') }}" method="post">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
      <div class="form-group">
        <input type="text" class="form-control" name="email" placeholder="邮箱">
      </div>
      <div class="form-group">
        <input type="password" class="form-control" name="password" placeholder="密码">
      </div>
      <div class="checkbox">
        <label>
          <input type="checkbox" name="remember" value="1">记住我
        </label>
      </div>
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          <div class="form-group">
            <ul>
              {% for message in messages %}
                <li class="text-danger">{{ message }}</li>
              {% endfor %}
            </ul>
          </div>
        {% endif %}
      {% endwith %}
      <div class="form-group">
        <button class="btn btn-warning btn-block" id="submit-btn">立即登录</button>
      </div>
      <div class="form-group">
        <a href="#" class="signup-link">没有账号？立即注册</a>
        <a href="#" class="resetpwd-link" style="float:right;">找回密码</a>
      </div>
    </form>
  </div>
{% endblock %}

templates/front/post_detail.html
{% extends 'front/base.html' %}

{% block title %}
  {{ post.title }}
{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{{ url_for('static',filename='front/css/post_detail.css') }}">
{% endblock %}

{% block body %}
  <div class="lg-container">
    <div class="post-container">
      <h2>{{ post.title }}</h2>
      <p class="post-info-group">
        <span>发表时间：{{ post.create_time }}</span>
        <span>作者：<a href="{{ url_for('user.profile',user_id=post.author.id) }}">{{ post.author.username }}</a></span>
        <span>所属板块：{{ post.board.name }}</span>
        <span>阅读数：{{ post.read_count }}</span>
        <span>评论数：{{ post.comments.count() }}</span>
      </p>
      <article class="post-content" id="post-content">
        {{ post.content|safe }}
      </article>
    </div>
    <div class="comment-group">
      <h3>评论列表</h3>
      <ul class="comment-list-group">
        {% for comment in post.comments.filter_by(is_active=True) %}
          <li>
            <div class="comment-content">
              <p class="author-info">
                <span>{{ comment.author.username }}</span>
                <span>{{ comment.create_time }}</span>
              </p>
              <p class="comment-txt">
                {{ comment.content }}
              </p>
            </div>
          </li>
        {% endfor %}
      </ul>
    </div>
    <div class="add-comment-group">
      <h3>发表评论</h3>
      <form action="{{ url_for('front.public_comment',post_id=post.id) }}" method="post">
        <textarea class="form-control" name="content" id="editor" cols="30" rows="5"></textarea>
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
        {% with messages = get_flashed_messages()  %}
          {% if messages %}
            {% for message in messages %}
              <div class="text-danger mt-2">{{ message }}</div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        <div class="comment-btn-group">
          <button class="btn btn-primary" id="comment-btn">发表评论</button>
        </div>
      </form>
    </div>
  </div>
  <div class="sm-container"></div>
{% endblock %}

templates/front/profile.html
{% extends 'front/base.html' %}

{% block title %}
  {{ user.username }}个人中心
{% endblock %}

{% block head %}
  <style>
  .profile-box{
    width: 400px;
    margin: 0 auto;
  }
  .avatar{
    width: 100px;
  }
  </style>
{% endblock %}

{% block body %}
  <div class="profile-box">
  <h1 style="text-align: center;">{{ user.username }}个人中心</h1>
    <form action="{{ url_for('user.edit_profile') }}" method="post" enctype="multipart/form-data">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
      <table class="table table-bordered mt-5">
        <tbody>
          <tr>
            <th width="100px">用户名：</th>
            <td>
              {% if is_mine %}
                <input type="text" name="username" value="{{ user.username }}">
              {% else %}
                {{ user.username }}
              {% endif %}
            </td>
          </tr>
          <tr>
            <th>头像：</th>
            <td>
              {% if user.avatar %}
                <img src="{{ user.avatar }}" alt="">
              {% else %}
                <img class="avatar" src="{{ avatars.gravatar(user.email|email_hash)|replace('https://gravatar.com/avatar/','https://cdn.v2ex.com/gravatar/') }}" alt="">
              {% endif %}
              {% if is_mine %}
                <input type="file" name="avatar" accept="image/jpeg, image/png" value="上传头像">
              {% endif %}
            </td>
          </tr>
          <tr>
            <th>签名：</th>
            <td>
              {% if is_mine %}
                <input type="text" name="signature" value="{{ user.signature or '' }}">
              {% else %}
                {{ user.signature or "" }}
              {% endif %}
            </td>
          </tr>
        </tbody>
      </table>
      {% if is_mine %}
        <div style="text-align: center;">
          <button class="btn btn-primary">保存</button>
        </div>
      {% endif %}
    </form>
  </div>
{% endblock %}

templates/front/public_post.html
{% extends "front/base.html" %}

{% block title %}
  发布帖子
{% endblock %}

{% block head %}
  <script src="https://cdn.jsdelivr.net/npm/wangeditor@latest/dist/wangEditor.min.js"></script>
  <script src="{{ url_for('static',filename='front/js/public_post.js') }}"></script>
{% endblock %}

{% block body %}
  <h1 style="text-align: center;">发布帖子</h1>
  <div class="mb-4"></div>
  <form action="" method="post">
    <div class="form-group">
      <label>标题</label>
      <input type="text" class="form-control" name="title">
    </div>
    <div class="form-group">
      <label>板块</label>
      <select name="board_id" class="form-control">
        {% for board in boards %}
          <option value="{{ board.id }}">{{ board.name }}</option>
        {% endfor %}
      </select>
    </div>
    <div class="form-group">
      <label>内容</label>
      <div id="editor"></div>
    </div>
    <div class="form-group">
      <button class="btn btn-danger" id="submit-btn">发布帖子</button>
    </div>
  </form>
{% endblock %}

templates/front/register.html
{% extends 'front/base.html' %}

{% block title %}
  知了课堂注册
{% endblock %}

{% block head %}
  <link rel="stylesheet" href="{{ url_for('static',filename='front/css/sign.css') }}">
  <script src="{{ url_for('static',filename='front/js/register.js') }}"></script>
{% endblock %}

{% block body %}
  <h1 class="page-title">注册</h1>
  <div class="sign-box">
    <form action="{{ url_for('user.register') }}" method="post" id="register-form">
      <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
      <div class="form-group">
        <div class="input-group">
          <input type="text" class="form-control" name="email" placeholder="邮箱">
          <div class="input-group-append">
            <button id="captcha-btn" class="btn btn-outline-secondary">发送验证码</button>
          </div>
        </div>
      </div>
      <div class="form-group">
        <input type="text" class="form-control" name="captcha" placeholder="邮箱验证码">
      </div>
      <div class="form-group">
        <input type="text" class="form-control" name="username" placeholder="用户名">
      </div>
      <div class="form-group">
        <input type="password" class="form-control" name="password" placeholder="密码">
      </div>
      <div class="form-group">
        <input type="password" class="form-control" name="confirm_password" placeholder="确认密码">
      </div>
      {% with messages = get_flashed_messages() %}
        {% if messages %}
          <div class="form-group">
            <ul>
              {% for message in messages %}
                <li class="text-danger">{{ message }}</li>
              {% endfor %}
            </ul>
          </div>
        {% endif %}
      {% endwith %}
      <div class="form-group">
        <button class="btn btn-warning btn-block" id="submit-btn">立即注册</button>
      </div>
      <div class="form-group">
        <a href="#" class="signup-link">返回登陆</a>
        <a href="#" class="resetpwd-link" style="float:right;">找回密码</a>
      </div>
    </form>
  </div>
{% endblock %}