models/post.py
from exts import db
from datetime import datetime


# 板块模型
class BoardModel(db.Model):
    __tablename__ = 'board'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.String(20), nullable=False)
    create_time = db.Column(db.DateTime, default=datetime.now)
    is_active = db.Column(db.Boolean, default=True)


class PostModel(db.Model):
    __tablename__ = 'post'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(200), nullable=False)
    content = db.Column(db.Text, nullable=False)
    create_time = db.Column(db.DateTime, default=datetime.now)
    read_count = db.Column(db.Integer, default=0)
    is_active = db.Column(db.Boolean, default=True)

    board_id = db.Column(db.Integer, db.ForeignKey('board.id'))
    author_id = db.Column(db.String(100), db.ForeignKey("user.id"), nullable=False)

    # 帖子对应一个板块，对应一个作者
    board = db.relationship("BoardModel", backref="posts")
    author = db.relationship("UserModel", backref="posts")


class CommentModel(db.Model):
    __tablename__ = 'comment'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    content = db.Column(db.Text, nullable=False)
    create_time = db.Column(db.DateTime, default=datetime.now)
    is_active = db.Column(db.Boolean, default=True)
    post_id = db.Column(db.Integer, db.ForeignKey("post.id"))
    author_id = db.Column(db.String(100), db.ForeignKey("user.id"), nullable=False)

    # 一个评论属于一条帖子，属于一个作者
    post = db.relationship("PostModel", backref=db.backref('comments', order_by=create_time.desc(), lazy="dynamic"))
    author = db.relationship("UserModel", backref='comments')

models/user.py
from enum import Enum
from exts import db
from datetime import datetime
from shortuuid import uuid
from werkzeug.security import generate_password_hash, check_password_hash


class UserModel(db.Model):
    __tablename__ = 'user'
    id = db.Column(db.String(100), primary_key=True, default=uuid)
    username = db.Column(db.String(50), nullable=False, unique=True)
    _password = db.Column(db.String(200), nullable=False)
    email = db.Column(db.String(50), nullable=False, unique=True)
    avatar = db.Column(db.String(100))
    signature = db.Column(db.String(100))

    join_time = db.Column(db.DateTime, default=datetime.now)
    is_staff = db.Column(db.Boolean, default=False)
    is_active = db.Column(db.Boolean, default=True)

    # 外键
    role_id = db.Column(db.Integer, db.ForeignKey('role.id'))
    role = db.relationship('RoleModel', backref='users')

    # 直接传password自动完成加密
    def __init__(self, *args, **kwargs):
        if "password" in kwargs:
            self.password = kwargs.get('password')
            kwargs.pop('password')
        super(UserModel, self).__init__(*args, **kwargs)

    @property
    def password(self):
        return self._password

    @password.setter
    def password(self, raw_password):
        self._password = generate_password_hash(raw_password)

    def check_password(self, raw_password):
        ans = check_password_hash(self.password, raw_password)
        return ans

    # 用来快速判断当前用户是否具有某个权限
    def has_permission(self, permission):
        return permission in [permission.name for permission in self.role.permissions]


class PermissionEnum(Enum):
    """
        存放权限类型的枚举
    """
    BOARD = '板块'
    POST = '帖子'
    COMMENT = '评论'
    FRONT_USER = '前台用户'
    CMS_USER = '后台用户'


class PermissionModel(db.Model):
    """
        用户权限表，权限的类型从PermissionEnum中获取,不是直接和用户关联，而是先跟角色关联再跟用户关联
    """
    __tablename__ = 'permission'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    name = db.Column(db.Enum(PermissionEnum), nullable=False, unique=True)


#
role_permission_table = db.Table(
    "role_permission_table",
    db.Column("role_id", db.Integer, db.ForeignKey('role.id')),
    db.Column("permission_id", db.Integer, db.ForeignKey("permission.id"))
)


class RoleModel(db.Model):
    """
        主键id， 角色描述desc， 创建时间，关系属性permissions与PermissionModel进行关联
        RoleModel和PermissionModel属于多对多的关系
        通过PermissionModel对象的roles属性即可访问到权限下所有与其关联的角色
    """
    __tablename__ = 'role'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    # 角色名称
    name = db.Column(db.String(50), nullable=False)
    # 角色描述
    desc = db.Column(db.String(200), nullable=True)
    # 创建时间
    create_time = db.Column(db.DateTime, default=datetime.now)
    # 拥有权限
    permissions = db.relationship('PermissionModel', secondary=role_permission_table, backref="roles")

forms/baseform.py
from wtforms import Form


# 用于从form.errors中提取所有字符串类型的错误信息
# 以后可以通过form.messages得到所有字符串类型的错误信息，用于传递给渲染模板
class BaseForm(Form):
    @property
    def messages(self):
        message_list = []
        if self.errors:
            for error in self.errors.values():
                message_list.extend(error)
        return message_list

forms/cms.py
from .baseform import BaseForm
from wtforms import StringField, IntegerField, BooleanField
from wtforms.validators import Email, InputRequired


class AddStaffForm(BaseForm):
    email = StringField(validators=[Email(message="请输入正确的邮箱")])
    role = IntegerField(validators=[InputRequired(message="请选择角色")])


class EditStaffForm(BaseForm):
    is_staff = BooleanField(validators=[InputRequired(message="请选择是否为员工")])
    role = IntegerField(validators=[InputRequired(message="请选择分组")])

forms/post.py
from .baseform import BaseForm
from wtforms import StringField, IntegerField
from wtforms.validators import InputRequired, Length


class PublicPostForm(BaseForm):
    title = StringField(validators=[Length(min=2, max=100, message="请输入正确长度的标题")])
    content = StringField(validators=[Length(min=2, message="请输入正确长度的内容")])
    board_id = IntegerField(validators=[InputRequired(message="请输入板块id")])


class PublicCommentForm(BaseForm):
    content = StringField(validators=[Length(min=2, max=200, message="请输入正确长度的评论")])

forms/user.py
from wtforms import StringField, ValidationError, BooleanField, FileField
from wtforms.validators import Email, EqualTo, Length
from exts import cache
from models.user import UserModel
from .baseform import BaseForm
from flask_wtf.file import FileAllowed


class EditProfileForm(BaseForm):
    username = StringField(validators=[Length(min=2, max=20, message="请输入正确格式的用户名")])
    avatar = FileField(validators=[FileAllowed(['jpg', 'jpeg', 'png'], message="文件类型错误")])
    signature = StringField()

    @staticmethod
    def validate_signature(field):
        signature = field.data
        if signature and len(signature) > 100:
            raise ValidationError(message="签名不能超过100个字符")


class LoginForm(BaseForm):
    email = StringField(validators=[Email(message='请输入正确格式的邮箱')])
    password = StringField(validators=[Length(min=6, max=20, message="请输入正确长度的密码")])
    remember = BooleanField()


class RegisterForm(BaseForm):
    email = StringField(validators=[Email(message="请输入正确格式的邮箱！")])
    captcha = StringField(validators=[Length(min=4, max=4, message="请输入正确的验证码")])
    username = StringField(validators=[Length(min=2, max=20, message="请输入正确长度的用户名")])
    password = StringField(validators=[Length(min=6, max=20, message="请输入正确长度的密码")])
    confirm_password = StringField(validators=[EqualTo("password", message="两次密码不一致")])

    @staticmethod
    def validate_email(field):
        email = field.data
        user = UserModel.query.filter_by(email=email).first()
        if user:
            raise ValidationError(message='邮箱已经存在')

    def validate_captcha(self, field):
        captcha = field.data
        email = self.email.data
        cache_captcha = cache.get(email)
        if not cache_captcha or captcha != cache_captcha:
            raise ValidationError(message="验证码错误")

blueprints/cms.py
from flask import Blueprint, render_template, g, redirect, request, flash, url_for
from models.user import PermissionEnum
from decorators import permission_required
from models.user import UserModel, RoleModel
from models.post import PostModel
from forms.cms import AddStaffForm, EditStaffForm
from exts import db
from utils import restful

bp = Blueprint('cms', __name__, url_prefix='/cms')


# 管理页面的视图函数
@bp.get("")
def index():
    return render_template("cms/index.html")


# 如果当前用户不是员工，则不允许访问
@bp.before_request
def cms_before_request():
    if not hasattr(g, "user") or g.user.is_staff is False:
        return redirect("/")


@bp.context_processor
def cms_context_processor():
    return {"PermissionEnum": PermissionEnum}


@bp.get("/staff/list")
@permission_required(PermissionEnum.CMS_USER)
def staff_list():
    users = UserModel.query.filter_by(is_staff=True).all()
    return render_template("cms/staff_list.html", users=users)


@bp.route("/staff/add", methods=['GET', 'POST'])
@permission_required(PermissionEnum.CMS_USER)
def add_staff():
    if request.method == "GET":
        roles = RoleModel.query.all()
        return render_template("cms/add_staff.html", roles=roles)
    else:
        form = AddStaffForm(request.form)
        if form.validate():
            email = form.email.data
            role_id = form.role.data
            user = UserModel.query.filter_by(email=email).first()
            if not user:
                flash("没有此用户")
                return redirect(url_for("cms.add_staff"))
            user.is_staff = True
            user.role = RoleModel.query.get(role_id)
            db.session.commit()
            return redirect(url_for("cms.staff_list"))


# 编辑员工
@bp.route("/staff/edit/<string:user_id>", methods=['GET', 'POST'])
@permission_required(PermissionEnum.CMS_USER)
def edit_staff(user_id):
    user = UserModel.query.get(user_id)
    if request.method == 'GET':
        roles = RoleModel.query.all()
        return render_template("cms/edit_staff.html", user=user, roles=roles)
    else:
        form = EditStaffForm(request.form)
        if form.validate():
            is_staff = form.is_staff.data
            role_id = form.role.data
            user.is_staff = is_staff
            if user.role.id != role_id:
                user.role = RoleModel.query.get(role_id)
            db.session.commit()
            return redirect(url_for("cms.edit_staff", user_id=user_id))
        else:
            for message in form.messages:
                flash(message)
            return redirect(url_for("cms.edit_staff", user_id=user_id))


@bp.route("/users")
@permission_required(PermissionEnum.FRONT_USER)
def user_list():
    users = UserModel.query.filter_by(is_staff=False).all()
    return render_template("cms/users.html", users=users)


@bp.post("/users/active/<string:user_id>")
@permission_required(PermissionEnum.FRONT_USER)
def active_user(user_id):
    is_active = request.form.get("is_active", type=int)
    if is_active is None:
        return restful.param_error(message="请传入is_active参数")
    user = UserModel.query.filter_by(user_id)
    user.is_active = bool(is_active)
    db.session.commit()
    return restful.ok()


@bp.get("/posts")
@permission_required(PermissionEnum.POST)
def post_list():
    posts = PostModel.query.all()
    return render_template("cms/posts.html", posts=posts)


@bp.post("/posts/active/<int:post_id>")
def active_post(post_id):
    is_active = request.form.get("is_active", type=int)
    if is_active is None:
        return restful.param_error(message="请输入is_active参数")
    post = PostModel.query.get(post_id)
    post.is_active = bool(is_active)
    db.session.commit()
    return restful.ok()

blueprints/user.py
import os
import random

from flask import Blueprint, render_template, request, current_app, redirect, url_for, flash, session, g
from exts import cache, db
from utils import restful
from forms.user import RegisterForm, LoginForm, EditProfileForm
from models.user import UserModel
from werkzeug.datastructures import CombinedMultiDict
from werkzeug.utils import secure_filename
from decorators import login_required

bp = Blueprint('user', __name__, url_prefix='/user')


@bp.route("/profile/edit")
@login_required
def edit_profile():
    form = EditProfileForm(CombinedMultiDict([request.form, request.files]))
    if form.validate():
        username = form.username.data
        avatar = form.avatar.data
        signature = form.signature.data
        # 如果上传了头像
        if avatar:
            # 生成安全的文件名
            filename = secure_filename(avatar.filename)
            # 拼接头像存储路径
            avatar_path = os.path.join(current_app.config.get("AVATARS_SAVE_PATH"), filename)
            # 保存文件
            avatar.save(avatar_path)
            # 设置头像的url
            g.user.avatar = url_for("media.media_file", filename=os.path.join("avatars", filename))
            g.user.username = username
            g.user.signature = signature
            db.session.commit()
            return redirect(url_for("user.profile", user_id=g.user_id))
        else:
            for message in form.messages:
                flash(message)
            return redirect(url_for("user.profile", user_id=g.user_id))


# 发送邮箱验证码，若发送成功，返回状态码200，否则返回状态码500
@bp.route('/mail/captcha')
def mail_captcha():
    try:
        email = request.args.get("mail")
        digits = [str(i) for i in list(range(0, 10))]
        captcha = ''.join(random.sample(digits, 4))
        subject = '注册验证码'
        body = "你的注册验证码是{}".format(captcha)
        current_app.celery.send_task('send_mail', (email, subject, body))

        # 将验证码存到redis
        cache.set(email, captcha, timeout=100)
        return restful.ok()
    except Exception as e:
        print(e)
        return restful.sever_error()


# 登录视图函数
@bp.route("/register", methods=['GET', 'POST'])
def register():
    if request.method == "GET":
        return render_template("front/register.html")
    else:
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            user = UserModel(email=email, username=username, password=password)

            db.session.add(user)
            db.session.commit()
            return redirect(url_for("user.login"))
        else:
            for message in form.messages:
                flash(message)
            return redirect(url_for("user.register"))


@bp.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == "GET":
        return render_template("front/login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            remember = form.remember.data
            user = UserModel.query.filter_by(email=email).first()
            if user and user.check_password(password):
                if not user.is_active:
                    flash("该用户已被禁用")
                    return redirect(url_for("user.login"))
                session['user_id'] = user.id
                if remember:
                    session.permanent = True
                return redirect("/")
            else:
                flash("邮箱或者密码错误")
                return redirect(url_for("user.login"))
        else:
            for message in form.messages:
                flash(message)
            return render_template("front/login.html")


@bp.route("/profile<string:user_id>")
def profile(user_id):
    user = UserModel.query.get(user_id)
    is_mine = False
    # 添加限制，访问自己的个人中心可以编辑，访问别人的个人中心不能编辑
    if hasattr(g, "user") and g.user == user_id:
        is_mine = True
    context = {
        'user': user,
        "is_mine": is_mine,
    }
    return render_template("front/profile.html", **context)


@bp.route("/logout")
def logout():
    session.clear()
    return redirect("/")

templates/cms/add_staff.html
{% extends "cms/base.html" %}

{% block title -%}
  添加员工
{%- endblock %}

{% block head %}
{% endblock %}

{% block page_title -%}
  {{ self.title() }}
{%- endblock %}

{% block main_content %}
  <form action="" method="post">
    <div class="form-container">
      <div class="form-group form-inline">
        <label for="email">邮箱：</label>
        <input id="email" type="email" class="form-control" name="email" placeholder="邮箱">
      </div>
      <div class="form-group">
        <label>角色：</label>
        {% for role in roles %}
          <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="role" id="inlineRadio{{ loop.index }}" value="{{ role.id }}">
            <label class="form-check-label" for="inlineRadio{{ loop.index }}">{{ role.name }}</label>
          </div>
        {% endfor %}
      </div>
      <div class="form-group">
        <button class="btn btn-primary" id="submit">立即添加</button>
      </div>
    </div>
  </form>
{% endblock %}

templates/cms/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <script src="https://cdn.bootcdn.net/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <link href="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.bootcdn.net/ajax/libs/twitter-bootstrap/4.6.0/js/bootstrap.min.js"></script>
  <script src="{{ url_for('static',filename='common/zlajax.js') }}"></script>
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{{ url_for('static',filename='cms/css/base.css') }}">
  {% block head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">知了CMS管理系统</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a href="{{ url_for('user.profile',user_id=g.user.id) }}" class="nav-link">{{ g.user.username }}</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/">前台首页</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ url_for('user.logout') }}">退出登录</a>
      </li>
    </ul>
  </div>
</nav>

<div class="main-body">
  <div class="left-body">
    <div class="sidebar">
      <ul class="nav-sidebar">
        <li class="unfold"><a href="{{ url_for('cms.index') }}">首页</a></li>
        {% set user = g.user %}
        {% if user.has_permission(PermissionEnum.POST) %}
          <li class="nav-group post-manage"><a href="{{ url_for('cms.post_list') }}">帖子管理</a></li>
        {% endif %}
        {% if user.has_permission(PermissionEnum.COMMENT) %}
          <li class="comments-manage"><a href="{{ url_for('cms.comment_list') }}">评论管理</a></li>
        {% endif %}
        {% if user.has_permission(PermissionEnum.BOARD) %}
          <li class="board-manage"><a href="{{ url_for('cms.board_list') }}">板块管理</a></li>
        {% endif %}
        {% if user.has_permission(PermissionEnum.FRONT_USER) %}
          <li class="nav-group user-manage"><a href="{{ url_for('cms.user_list') }}">用户管理</a></li>
        {% endif %}
        {% if user.has_permission(PermissionEnum.CMS_USER) %}
          <li class="nav-group UserModel-manage"><a href="{{ url_for('cms.staff_list') }}">员工管理</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
  <div class="right-body">
    <div class="main">
      <h1>{% block page_title %}{% endblock %}</h1>
      <div class="main_content">
        {% block main_content %}{% endblock %}
      </div>
    </div>
  </div>
</div>
</body>
</html>

templates/cms/boards.html
{% extends 'cms/base.html' %}

{% block title %}板块管理{% endblock %}

{% block head %}
  <script src="{{ url_for('static',filename='cms/js/boards.js') }}"></script>
{% endblock %}

{% block page_title %}
  {{ self.title() }}
{% endblock %}

{% block main_content %}
  <div class="top-box">
    <button class="btn btn-primary" style="float:right;" id="add-board-btn">添加新板块</button>
  </div>
  <table class="table table-bordered">
    <thead>
    <tr>
      <th>板块名称</th>
      <th>帖子数量</th>
      <th>创建时间</th>
      <th>操作</th>
    </tr>
    </thead>
    <tbody>
    {% for board in boards %}
      <tr data-name="{{ board.name }}" data-id="{{ board.id }}">
        <td>{{ board.name }}</td>
        <td>{{ board.posts|length }}</td>
        <td>{{ board.create_time }}</td>
        <td>
          <button class="btn btn-default btn-sm edit-board-btn" data-board-id="{{ board.id }}"
                  data-board-name="{{ board.name }}">编辑
          </button>
          <button class="btn btn-danger btn-sm delete-board-btn" data-board-id="{{ board.id }}"
                  data-board-name="{{ board.name }}">删除
          </button>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/cms/comments.html
{% extends 'cms/base.html' %}

{% block title %}评论管理{% endblock %}

{% block head %}
<script src="{{ url_for('static',filename='cms/js/comments.js') }}"></script>
{% endblock %}

{% block page_title %}
    {{ self.title() }}
{% endblock %}

{% block main_content %}
    <table class="table table-bordered">
    <thead>
    <tr>
      <th>内容</th>
      <th>发布时间</th>
      <th>所属帖子</th>
      <th>作者</th>
      <th>操作</th>
    </tr>
    </thead>
    <tbody>
    {% for comment in comments %}
      <tr>
        <td>{{ comment.content }}</td>
        <td>{{ comment.create_time }}</td>
        <td><a href="{{ url_for('front.post_detail',post_id=comment.post.id) }}">{{ comment.post.title }}</a></td>
        <td>{{ comment.author.username }}</td>
        <td>
          {% if comment.is_active %}
            <button class="btn btn-danger btn-sm active-btn" data-active="1" data-comment-id="{{ comment.id }}">隐藏</button>
          {% else %}
            <button class="btn btn-info btn-sm active-btn" data-active="0" data-comment-id="{{ comment.id }}">取消隐藏</button>
          {% endif %}
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/cms/edit_staff.html
{% extends "cms/base.html" %}

{% block title -%}
    编辑员工
{%- endblock %}

{% block head %}
{% endblock %}

{% block page_title -%}
    {{ self.title() }}
{%- endblock %}

{% block main_content %}
    <form action="" method="post">
        <div class="form-container">
            <div class="form-group form-inline">
                <label for="email">邮箱：</label>
                <input id="email" type="email" class="form-control" name="email" placeholder="邮箱" readonly
                       value="{{ user.email }}">
            </div>
            <div class="form-group">
                <label>员工：</label>
                <div class="form-check form-check-inline">
                    {% if user.is_staff %}
                        <input class="form-check-input" type="radio" name="is_staff" id="staff1" value="1" checked>
                    {% else %}
                        <input class="form-check-input" type="radio" name="is_staff" id="staff1" value="1">
                    {% endif %}
                    <label class="form-check-label" for="staff1" name="is_staff">是</label>
                </div>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="role" id="staff0" value="0">
                    <label class="form-check-label" for="staff0">否</label>
                </div>
            </div>
            <div class="form-group">
                <label>角色：</label>
                {% for role in roles %}
                    <div class="form-check form-check-inline">
                        {% if user.role.id == role.id %}
                            <input class="form-check-input" type="radio" name="role" id="inlineRadio{{ loop.index }}"
                                   value="{{ role.id }}" checked>
                        {% else %}
                            <input class="form-check-input" type="radio" name="role" id="inlineRadio{{ loop.index }}"
                                   value="{{ role.id }}">
                        {% endif %}
                        <label class="form-check-label" for="inlineRadio{{ loop.index }}">{{ role.name }}</label>
                    </div>
                {% endfor %}
            </div>
            <div class="form-group">
                <button class="btn btn-primary" id="submit">立即修改</button>
            </div>
        </div>
    </form>
{% endblock %}

templates/cms/index.html
{% extends 'cms/base.html' %}

{% block title %}
    知了CMS管理系统
{% endblock %}

{% block page_title %}
    欢迎来到知了CMS管理系统
{% endblock %}

templates/cms/posts.html
{% extends 'cms/base.html' %}

{% block title %}帖子管理{% endblock %}

{% block head %}
  <script src="{{ url_for('static',filename='cms/js/posts.js') }}"></script>
{% endblock %}

{% block page_title %}
  {{ self.title() }}
{% endblock %}

{% block main_content %}
  <table class="table table-bordered">
    <thead>
    <tr>
      <th>标题</th>
      <th>发布时间</th>
      <th>板块</th>
      <th>作者</th>
      <th>操作</th>
    </tr>
    </thead>
    <tbody>
    {% for post in posts %}
      <tr>
        <td><a target="_blank" href="{{ url_for("front.post_detail",post_id=post.id) }}">{{ post.title }}</a></td>
        <td>{{ post.create_time }}</td>
        <td>{{ post.board.name }}</td>
        <td>{{ post.author.username }}</td>
        <td>
          {% if post.is_active %}
            <button class="btn btn-danger btn-sm active-btn" data-active="1" data-post-id="{{ post.id }}">隐藏</button>
          {% else %}
            <button class="btn btn-info btn-sm active-btn" data-active="0" data-post-id="{{ post.id }}">取消隐藏</button>
          {% endif %}
        </td>
      </tr>
    {% endfor %}

    </tbody>
  </table>
{% endblock %}

templates/cms/staff_list.html
{% extends 'cms/base.html' %}

{% block title %}员工管理{% endblock %}

{% block head %}

{% endblock %}

{% block page_title %}
  {{ self.title() }}
{% endblock %}

{% block main_content %}
  <a href="{{ url_for('cms.add_staff') }}" class="btn btn-primary mb-3">添加员工</a>
  <table class="table table-bordered">
    <thead>
    <tr>
      <th>#</th>
      <th>邮箱</th>
      <th>用户名</th>
      <th>加入时间</th>
      <th>角色</th>
      <th>操作</th>
    </tr>
    </thead>
    <tbody>
    {% for user in users %}
      <tr>
        <td>{{ loop.index }}</td>
        <td>{{ user.email }}</td>
        <td>{{ user.username }}</td>
        <td>{{ user.join_time }}</td>
        <td>{{ user.role.name }}</td>
        <td>
          {% if not user.has_permission(PermissionEnum.CMS_USER) %}
            <a href="{{ url_for('cms.edit_staff',user_id=user.id) }}" class="btn btn-info btn-sm">编辑</a>
          {% endif %}
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock %}

templates/cms/users.html
{% extends 'cms/base.html' %}

{% block title %}用户管理{% endblock %}

{% block head %}
  <script src="{{ url_for('static',filename='cms/js/users.js') }}"></script>
{% endblock %}

{% block page_title %}
  {{ self.title() }}
{% endblock %}

{% block main_content %}
  <table class="table table-bordered">
    <thead>
    <tr>
      <th>#</th>
      <th>邮箱</th>
      <th>用户名</th>
      <th>加入时间</th>
      <th>操作</th>
    </tr>
    </thead>
    <tbody>
    {% for user in users %}
      <tr>
        <td>{{ loop.index }}</td>
        <td>{{ user.email }}</td>
        <td>{{ user.username }}</td>
        <td>{{ user.join_time }}</td>
        <td>
          {% if user.is_active %}
            <button class="btn btn-danger btn-sm active-btn" data-active="1" data-user-id="{{ user.id }}">禁用</button>
          {% else %}
            <button class="btn btn-info btn-sm active-btn" data-active="0" data-user-id="{{ user.id }}">取消禁用</button>
          {% endif %}
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>
{% endblock %}